@startuml flow_work
digraph G {
    mag [label="Magazyn"]
    pp [label="Pick and place"]
    recz [label="Stanowisko ręcznego\nukładania elementów", style=dashed]
    sito [label="Stanowisko z sitodrukiem"]
    piec [label="Piec lutowniczy"]
    stacja [label="Stacja do lutowania recznego", style=dashed]
    kon [label="Kontrola wizualna"]

    mag -> sito ->pp -> recz -> piec -> stacja -> kon [color=red]
    mag -> stacja
    mag -> pp
}
@enduml
