@startuml brute_force
skinparam monochrome true
skinparam shadowing false
skinparam defaultTextAlignment center

start
:Pobierz zadania do wykonania;
:Wygeneruj wszystkie permutacje|
while (Czy ten czas jest krótszy?) is (Tak)
  :Wczytaj permutacje zadań;
  :Oblicz moment ostatniego zadania;
  if (Czy jest to najkrótszy czas?) then (Tak)
    :Zapisz ten czas;
  else (Nie)
  endif
endwhile (Nie)
:Zwróć najlepsze rozwiązanie - permutację zadań;
end

@enduml